SELECT DISTINCT A.CART_ID 
FROM 
   (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = '우유') AS A
   JOIN
   (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = '요거트') AS B
WHERE A.CART_ID = B.CART_ID
ORDER BY A.CART_ID
